### ISSUE TITLE
Broken list sorting

### ISSUE THREAD

**Issue by romanblanco** [ManageIQ/manageiq-ui-self_service#13] opened 2016-02-24 15:07 UTC
I was trying to sort items in list alphabetically and noticed that sorting is not switchnig between two states (A-Z, Z-A), but sometimes in 3, sometimes in 4 different states.

___

**Screenshots** from one screen after repeated switching of sorting:

![screencapture-localhost-3001-self_service-marketplace-1456326228904](https://cloud.githubusercontent.com/assets/1187051/13289473/7af2e192-db10-11e5-8b01-506a495b8129.png)
![screencapture-localhost-3001-self_service-marketplace-1456326215203](https://cloud.githubusercontent.com/assets/1187051/13289477/7cdcab3c-db10-11e5-9178-4ce3c12a2a6f.png)
![screencapture-localhost-3001-self_service-marketplace-1456326220651](https://cloud.githubusercontent.com/assets/1187051/13289479/7dee31da-db10-11e5-9bc2-a1d894923db2.png)
![screencapture-localhost-3001-self_service-marketplace-1456326204445](https://cloud.githubusercontent.com/assets/1187051/13289480/7f020358-db10-11e5-9bcc-9eb9b341296b.png)

**Comment by chriskacerguis** [comment] 2016-09-15 01:05
@serenamarie125 can we get someone to look at this?

**Comment by chriskacerguis** [comment] 2016-09-27 00:50
@AllenBW here too.

**Comment by AllenBW** [comment] 2016-09-29 16:42
@romanblanco  I am unable to reproduce this issue, 
@chriskacerguis looks like it might have been resolved since first being reported, unable to reproduce

**Comment by chriskacerguis** [comment] 2016-09-29 19:19
Cools.  Going to close this issue.  @romanblanco please feel free to re-open in you need to.

**Closed by chriskacerguis** 2016-09-29 19:19 UTC
Labels: bug
